BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Parachute"
paginate = 5
DisqusShortname = "Parachute"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "syui"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "社会人大学院生の勉強会メモなど"
  cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
